# Generated by Django 4.2.5 on 2023-10-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guild', '0002_guild_faction_guild_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='faction',
            field=models.CharField(choices=[('Alliance', 'Alliance'), ('Horde', 'Horde')], max_length=50),
        ),
        migrations.AlterField(
            model_name='guild',
            name='server',
            field=models.CharField(choices=[('Arugal', 'Arugal'), ('Yojamba', 'Yojamba'), ('Remulos', 'Remulos')], max_length=50),
        ),
    ]
