# Generated by Django 4.2.5 on 2023-10-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guild', '0003_alter_guild_faction_alter_guild_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='characterGuild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guild.guild'),
        ),
    ]
