# Generated by Django 4.2.5 on 2023-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guild', '0004_alter_character_characterguild'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='characterFaction',
            field=models.CharField(choices=[('Alliance', 'Alliance'), ('Horde', 'Horde')], default='Alliance', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='characterRealm',
            field=models.CharField(choices=[('Arugal', 'Arugal'), ('Yojamba', 'Yojamba'), ('Remulos', 'Remulos')], default='Arugal', max_length=50),
            preserve_default=False,
        ),
    ]
