# Generated by Django 4.2.6 on 2023-10-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guild', '0005_character_characterfaction_character_characterrealm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
                ('instance_type', models.CharField(choices=[('10', '10'), ('25', '25'), ('Dungeon', 'Dungeon'), ('Heroic', 'Heroic'), ('Mythic', 'Mythic'), ('Mythic+', 'Mythic+'), ('Mythic++', 'Mythic++'), ('Mythic+++', 'Mythic+++'), ('Mythic++++', 'Mythic++++')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstanceBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guild.instance')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceLoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=20)),
                ('item_level', models.IntegerField()),
                ('wowhead_link', models.URLField()),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guild.instanceboss')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guild.instance')),
            ],
        ),
    ]
